function findTheDifference(s: string, t: string): string {
  let result: number = 0;
  for (let i = 0; i < s.length; i++) {
    result ^= s[i].charCodeAt(0) ^ t[i].charCodeAt(0);
  }
  result ^= t[t.length - 1].charCodeAt(0);
  return String.fromCharCode(result);
}

const s = "abcd";
const t = "abcde";
const output = findTheDifference(s, t);
console.log(output);

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
